### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tmsagarofficial**

### CODE REVIEW

**Review by GANESHSHARMA1 — APPROVED** [review]

**Comment by tmsagarofficial** [comment]
Hi

**Comment by tmsagarofficial** [comment]
Thanks man

**Comment by tmsagarofficial** [comment]
GetPlaced 🚀

**Comment by GANESHSHARMA1** [comment]
> GetPlaced 🚀

@tmsagarofficial ✌🎉

**Pull request merged**
